inital commit
ProninDenys/Forms pull request #1
Opened 2024-06-07 18:48 UTC by ProninDenys

2024-06-11 14:53 UTC, a1exalexander requested changes
Дуже добре! Трішки треба поправити дещо

2024-06-11 14:53 UTC, a1exalexander commented on index.html
> +          required
не може бути два поля з однаковим `name`! Відправиться лише одне поле! однаковий `name` може бути лише для `checkbox` та `radio`

Зміни другий password та password2

2024-06-11 14:53 UTC, a1exalexander commented on index.html
> +      </li>
це має бути `checkbox`

2024-06-11 14:53 UTC, a1exalexander commented on index.html
> +    <button type="submit">Сlear form</button>         <button type="submit">Sign up</button>
```suggestion
    <button type="reset">Сlear form</button>         <button type="submit">Sign up</button>
```
```suggestion
    <button type="submit">Сlear form</button>         <button type="submit">Sign up</button>
```

2024-06-11 20:58 UTC, ProninDenys commented
исправил 
добавил второй комит

2024-06-13 12:23 UTC, a1exalexander approved these changes
не потрібно робити два checkbox, оскільки його логіка така, ти або вибрав або ні!
не потрібно на один елемент додавати два атрибута однакових
![image](https://github.com/ProninDenys/Forms/assets/40409129/73a17ba6-e7a1-4440-a829-c4ec42cf2fc1)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
https://www.w3schools.com/tags/att_input_type_checkbox.asp

2024-06-13 18:25 UTC, merged